In [2]:
# Padding test
from cnn import max_pooling, forward, zero_pad, conv_backward
import numpy as np

w_test_array = np.random.randn(1, 10, 10, 3)
b_test_array = np.random.randn(8)

w_pad = zero_pad(w_test_array, 1)

print(w_pad)

[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 1.83147605  0.62405709 -1.13384548]
   [-1.17309671 -0.86562267 -0.05373233]
   [ 0.26997739 -0.40926441  1.18665456]
   [-0.24827734  2.43626388 -0.68396911]
   [ 0.67949824 -0.19368128 -0.08383368]
   [-0.30805894  0.54649093  1.36094262]
   [ 0.00344188 -0.3691867  -0.59182892]
   [-1.26056754 -0.31267928  1.5671178 ]
   [ 0.71167192 -0.34800841 -0.69932914]
   [ 0.70931856  0.23836884  1.92263575]
   [ 0.          0.          0.        ]]

  [[ 0.     

In [3]:
# Forward prop test
A_prev = np.random.randn(10, 32, 32, 3)
W = np.random.randn(5, 5, 3, 8)
b = np.random.randn(1, 1, 1, 8)
hparameters = {'stride' : 2, 'pad' : 2}

Z, cache = forward(A_prev, W, b, hparameters)

print(Z.shape)
print(type(cache))
print(len(cache))



(10, 16, 16, 8)
<class 'tuple'>
4


In [8]:
# Max pooling test
pool_test_array = np.random.randn(10, 5, 5, 2)
hparameters = {'stride' : 1, 'f' : 3}
pool_result, cache = max_pooling(pool_test_array, hparameters)

print(pool_result.shape)
print(type(cache))
print(len(cache))

(10, 3, 3, 2)
<class 'tuple'>
2


In [6]:
# Backpropagation in conv layer test
conv_backprop_test = np.random.randn(3, 10, 10, 7)

dA_prev, dW, db = conv_backward(conv_backprop_test, cache)
print(dA_prev.shape)
print(dW.shape)
print(db.shape)


(10, 32, 32, 3)
(5, 5, 3, 8)
(1, 1, 1, 8)
