In [3]:
# Padding test
from cnn import zero_pad, FCLayer
import numpy as np

w_test_array = np.random.randn(1, 10, 10, 3)
b_test_array = np.random.randn(8)

w_pad = zero_pad(w_test_array, 1)

print(w_pad)

[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [-8.47133869e-01 -5.27099257e-01 -8.09290138e-01]
   [-2.52269013e-01  1.01499484e+00 -7.60196109e-01]
   [ 1.41198614e+00 -1.06899962e+00  7.59161110e-01]
   [ 1.15246992e+00  1.31005154e+00 -8.51035093e-01]
   [ 3.47486247e-01 -3.92935883e-01 -4.96972421e-01]
   [-3.23238232e-01  3.33295800e-02 -1.16946

In [3]:
# Forward prop test
A_prev = np.random.randn(10, 32, 32, 3)
W = np.random.randn(5, 5, 3, 8)
b = np.random.randn(1, 1, 1, 8)
hparameters = {'stride' : 2, 'pad' : 2}

Z, cache = forward(A_prev, W, b, hparameters)

print(Z.shape)
print(type(cache))
print(len(cache))



(10, 16, 16, 8)
<class 'tuple'>
4


In [8]:
# Max pooling test
pool_test_array = np.random.randn(10, 5, 5, 2)
hparameters = {'stride' : 1, 'f' : 3}
pool_result, cache = max_pooling(pool_test_array, hparameters)

print(pool_result.shape)
print(type(cache))
print(len(cache))

(10, 3, 3, 2)
<class 'tuple'>
2


In [6]:
# Backpropagation in conv layer test
conv_backprop_test = np.random.randn(3, 10, 10, 7)

dA_prev, dW, db = conv_backward(conv_backprop_test, cache)
print(dA_prev.shape)
print(dW.shape)
print(db.shape)


(10, 32, 32, 3)
(5, 5, 3, 8)
(1, 1, 1, 8)


In [14]:
mlp_layer = FCLayer(50, 20, 'relu')

X = np.random.randn(2*5*5, 10)
print(X.shape)

A = mlp_layer.forward(X)
print(A)

(50, 10)
None
